#! /bin/bash
#BENCHEIKH Sabrina et BOUAZIZ Mohammed Amine
#Cette commande calcule et affiche le signe zodiacal correspondant à une date donnée.



function isnum ()
#fonction qui renvoie 0 (vrai) quand l'argument qui lui est passé en paramètre est un nombre (positif ou négatif), 1 sinon
{
   if [[ "$1" =~ ^[-+]?[0-9]+$ ]]; then
   	return 0
   	else
        return 1
   fi
}

function aide ()
# affiche l'aide de la commande (si $1 = "--help")
{
	echo "usage : signezodiaque affiche le signe zodiacal correspondant à une date donnée"
	echo "verifie que chaque parametre est un entier"
	echo "vérifier que la date est valide"
	echo "exemple: signezodiaque JJ MM"
	return 0
}


function dateval ()
#fonction qui renvoie 1 si la date est valide , 0 sinon (dans le cas ou $1 (le jours) ne serait pas dans l'interval exigé à savoir >0 et <jourmax du mois en question)
#Vu qu'on a listé tous les cas possible si les parametre ne se trouve dans aucun des cas possibles on renverra à la fin 0 ce qui equivaut à faux.
{

case "$2" in
 
 "1" | "3" | "5" | "7"| "8" | "10" | "12" | "01"| "03" | "05" | "07" | "08") 

   if [ $1 -gt 31 ] || [ $1 -le 0 ];then
   	return 0
   	else 
   	return 1
   fi
   ;;

  
  "4" | "6" | "9" | "11" | "04" | "06" | "09" )     
   if [ $1 -gt 30 ] || [ $1 -le 0 ];then
   	return 0
  	else 
   	return 1
   fi
   ;;
 
  "2" | "02" )    

   if [ $1 -gt 29 ] || [ $1 -le 0 ];then
   	return 0
   	else 
   	return 1
   fi
   ;;

* )
return 0
;;

esac
}



# programme principal



if [ $# -eq 0 ]; then 						# On vérifis la présence des parametres souhaités
   echo "pas de parametre !" >&2
   aide
elif [ $1 = "--help" ] ; then					# On affiche l'aide si le parametre entré est --help
	aide 


elif  ! isnum $1 ; then
	echo " Veuillez saisir un entier en P1!" >&2		#On appel la fonction isnum pour vérifier que les parametres $1 et $2 sont des entiers
   	aide 

elif  ! isnum $2 ; then
	echo " Veuillez saisir un entier  en P2!" >&2
   	aide 
 

elif   dateval $* ;then						# On appel la fonction dateval des parametres $1 $2 entrés pour vérifier leur validité
	echo "la date saisie n'est pas valide">&2
	aide


								# S'il on a noté aucune erreur on execute les instructions suivantes
else
#repertorier les signe dans un tableau : signe, jours et mois.
T_s=([0]="Capricorne" [1]="Verseau" [2]="Poisson" [3]="Bellier" [4]="Taureau" [5]="Gemeaux" [6]="Cancer" [7]="Lion" [8]="Vierge" [9]="Balance" [10]="Scorpion" [11]="Sagittaire" [12]="Capicorne" )
T_j=([0]=1 [1]=22 [2]=21 [3]=20 [4]=21 [5]=21 [6]=22 [7]=22 [8]=23 [9]=24 [10]=24 [11]=24 [12]=23)
T_m=([0]=1 [1]=1 [2]=2 [3]=3 [4]=4 [5]=5 [6]=6 [7]=7 [8]=8 [9]=9 [10]=10 [11]=11 [12]=12)

# On parcourera les deux tableaux jour et mois avec les données $1 et $2. 
# L'Algorithme : On avancera dans les tableaux jusqu'a lg-1 (ici 12) et tant qu'on a pas trouvé le bon interval pour les parametres $1 $2.
# On affichera le signe situé au même indice ou se trouve le jour et le mois entrés en parametres.
i=0
while (([ $i -le 12 ]) && !(([ $1 -ge ${T_j[i]} ] && [ $2 -eq ${T_m[i]} ]) || ([ $1 -lt ${T_j[i+1]} ] && [ $2 -eq ${T_m[i+1]} ])));
	do
	((i++))
done
	echo "${T_s[$i]}"

	
fi










